openapi: 3.0.1
info:
  title: Mes Auto
  description: auto api
  contact:
    email: ixtf1984@gmail.com
  version: '3.0'
security:
- bearerAuth: []
tags:
- name: auth
  description: 登录和权限
- name: api
- name: config
  description: 配置
- name: admin
  description: 管理员
- name: riamb
  description: 北自所接口
- name: if
  description: 接口
paths:
  /:
    get:
      tags:
      - auth
      summary: 获取
      description: sdfsf
      operationId: get
      parameters:
      - name: test
        in: query
        required: true
        schema:
          type: string
      responses:
        200:
          description: ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TResult'
        400:
          $ref: '#/components/responses/JException'
components:
  schemas:
    JException:
      type: object
      properties:
        errorCode:
          type: string
          example: E00000
        errorMessage:
          type: string
    TResult:
      type: object
      properties:
        name:
          type: string
  responses:
    JException:
      description: |
        非200的异常一般都会处理过，没处理的都是http status默认

        如：401没认证，403没权限，404找不到，等等
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/JException'
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
